export const provinces = {
  Afghanistan: [],
  "Aland Islands": [],
  Albania: [],
  Algeria: [],
  Andorra: [],
  Angola: [],
  Anguilla: [],
  "Antigua And Barbuda": [],
  Argentina: [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Ciudad Autónoma de Buenos Aires",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago Del Estero",
    "Tierra Del Fuego",
    "Tucumán",
  ],
  Armenia: [],
  Aruba: [],
  "Ascension Island": [],
  Australia: [
    "Australian Capital Territory",
    "New South Wales",
    "Northern Territory",
    "Queensland",
    "South Australia",
    "Tasmania",
    "Victoria",
    "Western Australia",
  ],
  Austria: [],
  Azerbaijan: [],
  Bahamas: [],
  Bahrain: [],
  Bangladesh: [],
  Barbados: [],
  Belarus: [],
  Belgium: [],
  Belize: [],
  Benin: [],
  Bermuda: [],
  Bhutan: [],
  Bolivia: [],
  "Bosnia And Herzegovina": [],
  Botswana: [],
  "Bouvet Island": [],
  Brazil: [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Pará",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Rio de Janeiro",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rondônia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins",
  ],
  "British Indian Ocean Territory": [],
  Brunei: [],
  Bulgaria: [],
  "Burkina Faso": [],
  Burundi: [],
  Cambodia: [],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
  ],
  "Cape Verde": [],
  "Caribbean Netherlands": [],
  "Cayman Islands": [],
  "Central African Republic": [],
  Chad: [],
  Chile: [
    "Arica and Parinacota",
    "Tarapacá",
    "Antofagasta",
    "Atacama",
    "Coquimbo",
    "Valparaíso",
    "Santiago",
    "O’Higgins",
    "Maule",
    "Ñuble",
    "Biobío",
    "Araucanía",
    "Los Ríos",
    "Los Lagos",
    "Aysén",
    "Magallanes",
  ],
  China: [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Inner Mongolia",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Ningxia",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Tianjin",
    "Xinjiang",
    "Xizang",
    "Yunnan",
    "Zhejiang",
  ],
  "Christmas Island": [],
  "Cocos (Keeling) Islands": [],
  Colombia: [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlántico",
    "Bogotá, D.C.",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "Cesar",
    "Chocó",
    "Córdoba",
    "Cundinamarca",
    "Guainía",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Andrés, Providencia y Santa Catalina",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada",
  ],
  Comoros: [],
  Congo: [],
  "Congo, The Democratic Republic Of The": [],
  "Cook Islands": [],
  "Costa Rica": [],
  Croatia: [],
  Cuba: [],
  Curaçao: [],
  Cyprus: [],
  "Czech Republic": [],
  "Côte d’Ivoire": [],
  Denmark: [],
  Djibouti: [],
  Dominica: [],
  "Dominican Republic": [],
  Ecuador: [],
  Egypt: [
    "6th of October",
    "Al Sharqia",
    "Alexandria",
    "Aswan",
    "Asyut",
    "Beheira",
    "Beni Suef",
    "Cairo",
    "Dakahlia",
    "Damietta",
    "Faiyum",
    "Gharbia",
    "Giza",
    "Helwan",
    "Ismailia",
    "Kafr el-Sheikh",
    "Luxor",
    "Matrouh",
    "Minya",
    "Monufia",
    "New Valley",
    "North Sinai",
    "Port Said",
    "Qalyubia",
    "Qena",
    "Red Sea",
    "Sohag",
    "South Sinai",
    "Suez",
  ],
  "El Salvador": [],
  "Equatorial Guinea": [],
  Eritrea: [],
  Estonia: [],
  Eswatini: [],
  Ethiopia: [],
  "Falkland Islands (Malvinas)": [],
  "Faroe Islands": [],
  Fiji: [],
  Finland: [],
  France: [],
  "French Guiana": [],
  "French Polynesia": [],
  "French Southern Territories": [],
  Gabon: [],
  Gambia: [],
  Georgia: [],
  Germany: [],
  Ghana: [],
  Gibraltar: [],
  Greece: [],
  Greenland: [],
  Grenada: [],
  Guadeloupe: [],
  Guatemala: [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa",
  ],
  Guernsey: [],
  Guinea: [],
  "Guinea Bissau": [],
  Guyana: [],
  Haiti: [],
  "Heard Island And Mcdonald Islands": [],
  "Holy See (Vatican City State)": [],
  Honduras: [],
  "Hong Kong": ["Hong Kong Island", "Kowloon", "New Territories"],
  Hungary: [],
  Iceland: [],
  India: [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli",
    "Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
  Indonesia: [
    "Aceh",
    "Bali",
    "Bangka Belitung",
    "Banten",
    "Bengkulu",
    "Gorontalo",
    "Jakarta",
    "Jambi",
    "Jawa Barat",
    "Jawa Tengah",
    "Jawa Timur",
    "Kalimantan Barat",
    "Kalimantan Selatan",
    "Kalimantan Tengah",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Kepulauan Riau",
    "Lampung",
    "Maluku",
    "Maluku Utara",
    "North Sumatra",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Papua",
    "Papua Barat",
    "Riau",
    "South Sumatra",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tengah",
    "Sulawesi Tenggara",
    "Sulawesi Utara",
    "West Sumatra",
    "Yogyakarta",
  ],
  "Iran, Islamic Republic Of": [],
  Iraq: [],
  Ireland: [
    "Carlow",
    "Cavan",
    "Clare",
    "Cork",
    "Donegal",
    "Dublin",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Limerick",
    "Longford",
    "Louth",
    "Mayo",
    "Meath",
    "Monaghan",
    "Offaly",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow",
  ],
  "Isle Of Man": [],
  Israel: [],
  Italy: [
    "Agrigento",
    "Alessandria",
    "Ancona",
    "Aosta",
    "Arezzo",
    "Ascoli Piceno",
    "Asti",
    "Avellino",
    "Bari",
    "Barletta-Andria-Trani",
    "Belluno",
    "Benevento",
    "Bergamo",
    "Biella",
    "Bologna",
    "Bolzano",
    "Brescia",
    "Brindisi",
    "Cagliari",
    "Caltanissetta",
    "Campobasso",
    "Carbonia-Iglesias",
    "Caserta",
    "Catania",
    "Catanzaro",
    "Chieti",
    "Como",
    "Cosenza",
    "Cremona",
    "Crotone",
    "Cuneo",
    "Enna",
    "Fermo",
    "Ferrara",
    "Firenze",
    "Foggia",
    "Forlì-Cesena",
    "Frosinone",
    "Genova",
    "Gorizia",
    "Grosseto",
    "Imperia",
    "Isernia",
    "L’Aquila",
    "La Spezia",
    "Latina",
    "Lecce",
    "Lecco",
    "Livorno",
    "Lodi",
    "Lucca",
    "Macerata",
    "Mantova",
    "Massa-Carrara",
    "Matera",
    "Medio Campidano",
    "Messina",
    "Milano",
    "Modena",
    "Monza e Brianza",
    "Napoli",
    "Novara",
    "Nuoro",
    "Ogliastra",
    "Olbia-Tempio",
    "Oristano",
    "Padova",
    "Palermo",
    "Parma",
    "Pavia",
    "Perugia",
    "Pesaro e Urbino",
    "Pescara",
    "Piacenza",
    "Pisa",
    "Pistoia",
    "Pordenone",
    "Potenza",
    "Prato",
    "Ragusa",
    "Ravenna",
    "Reggio Calabria",
    "Reggio Emilia",
    "Rieti",
    "Rimini",
    "Roma",
    "Rovigo",
    "Salerno",
    "Sassari",
    "Savona",
    "Siena",
    "Siracusa",
    "Sondrio",
    "Taranto",
    "Teramo",
    "Terni",
    "Torino",
    "Trapani",
    "Trento",
    "Treviso",
    "Trieste",
    "Udine",
    "Varese",
    "Venezia",
    "Verbano-Cusio-Ossola",
    "Vercelli",
    "Verona",
    "Vibo Valentia",
    "Vicenza",
    "Viterbo",
  ],
  Jamaica: [],
  Japan: [
    "Hokkaidō",
    "Aomori",
    "Iwate",
    "Miyagi",
    "Akita",
    "Yamagata",
    "Fukushima",
    "Ibaraki",
    "Tochigi",
    "Gunma",
    "Saitama",
    "Chiba",
    "Tōkyō",
    "Kanagawa",
    "Niigata",
    "Toyama",
    "Ishikawa",
    "Fukui",
    "Yamanashi",
    "Nagano",
    "Gifu",
    "Shizuoka",
    "Aichi",
    "Mie",
    "Shiga",
    "Kyōto",
    "Ōsaka",
    "Hyōgo",
    "Nara",
    "Wakayama",
    "Tottori",
    "Shimane",
    "Okayama",
    "Hiroshima",
    "Yamaguchi",
    "Tokushima",
    "Kagawa",
    "Ehime",
    "Kōchi",
    "Fukuoka",
    "Saga",
    "Nagasaki",
    "Kumamoto",
    "Ōita",
    "Miyazaki",
    "Kagoshima",
    "Okinawa",
  ],
  Jersey: [],
  Jordan: [],
  Kazakhstan: [],
  Kenya: [],
  Kiribati: [],
  "Korea, Democratic People’s Republic Of": [],
  Kosovo: [],
  Kuwait: [],
  Kyrgyzstan: [],
  "Lao People’s Democratic Republic": [],
  Latvia: [],
  Lebanon: [],
  Lesotho: [],
  Liberia: [],
  "Libyan Arab Jamahiriya": [],
  Liechtenstein: [],
  Lithuania: [],
  Luxembourg: [],
  Macao: [],
  Madagascar: [],
  Malawi: [],
  Malaysia: [
    "Johor",
    "Kedah",
    "Kelantan",
    "Kuala Lumpur",
    "Labuan",
    "Melaka",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Putrajaya",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu",
  ],
  Maldives: [],
  Mali: [],
  Malta: [],
  Martinique: [],
  Mauritania: [],
  Mauritius: [],
  Mayotte: [],
  Mexico: [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Ciudad de México",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
  ],
  "Moldova, Republic of": [],
  Monaco: [],
  Mongolia: [],
  Montenegro: [],
  Montserrat: [],
  Morocco: [],
  Mozambique: [],
  Myanmar: [],
  Namibia: [],
  Nauru: [],
  Nepal: [],
  Netherlands: [],
  "Netherlands Antilles": [],
  "New Caledonia": [],
  "New Zealand": [
    "Auckland",
    "Bay of Plenty",
    "Canterbury",
    "Chatham Islands",
    "Gisborne",
    "Hawke’s Bay",
    "Manawatu-Wanganui",
    "Marlborough",
    "Nelson",
    "Northland",
    "Otago",
    "Southland",
    "Taranaki",
    "Tasman",
    "Waikato",
    "Wellington",
    "West Coast",
  ],
  Nicaragua: [],
  Niger: [],
  Nigeria: [
    "Abia",
    "Abuja Federal Capital Territory",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara",
  ],
  Niue: [],
  "Norfolk Island": [],
  "North Macedonia": [],
  Norway: [],
  Oman: [],
  Pakistan: [],
  "Palestinian Territory, Occupied": [],
  Panama: [
    "Bocas del Toro",
    "Chiriquí",
    "Coclé",
    "Colón",
    "Darién",
    "Emberá",
    "Herrera",
    "Kuna Yala",
    "Los Santos",
    "Ngöbe-Buglé",
    "Panamá",
    "Panamá Oeste",
    "Veraguas",
  ],
  "Papua New Guinea": [],
  Paraguay: [],
  Peru: [
    "Amazonas",
    "Áncash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cuzco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima (departamento)",
    "Lima (provincia)",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali",
  ],
  Philippines: [
    "Abra",
    "Agusan del Norte",
    "Agusan del Sur",
    "Aklan",
    "Albay",
    "Antique",
    "Apayao",
    "Aurora",
    "Basilan",
    "Bataan",
    "Batanes",
    "Batangas",
    "Benguet",
    "Biliran",
    "Bohol",
    "Bukidnon",
    "Bulacan",
    "Cagayan",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguin",
    "Capiz",
    "Catanduanes",
    "Cavite",
    "Cebu",
    "Cotabato",
    "Davao de Oro",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Dinagat Islands",
    "Eastern Samar",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Kalinga",
    "La Union",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "Leyte",
    "Maguindanao",
    "Marinduque",
    "Masbate",
    "Metro Manila",
    "Misamis Occidental",
    "Misamis Oriental",
    "Mountain Province",
    "Negros Occidental",
    "Negros Oriental",
    "Northern Samar",
    "Nueva Ecija",
    "Nueva Vizcaya",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Pampanga",
    "Pangasinan",
    "Quezon",
    "Quirino",
    "Rizal",
    "Romblon",
    "Samar",
    "Sarangani",
    "Siquijor",
    "Sorsogon",
    "South Cotabato",
    "Southern Leyte",
    "Sultan Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tarlac",
    "Tawi-Tawi",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
  Pitcairn: [],
  Poland: [],
  Portugal: [
    "Açores",
    "Aveiro",
    "Beja",
    "Braga",
    "Bragança",
    "Castelo Branco",
    "Coimbra",
    "Évora",
    "Faro",
    "Guarda",
    "Leiria",
    "Lisboa",
    "Madeira",
    "Portalegre",
    "Porto",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Vila Real",
    "Viseu",
  ],
  Qatar: [],
  "Republic of Cameroon": [],
  Reunion: [],
  Romania: [
    "Alba",
    "Arad",
    "Argeș",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoșani",
    "Brașov",
    "Brăila",
    "București",
    "Buzău",
    "Călărași",
    "Caraș-Severin",
    "Cluj",
    "Constanța",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Iași",
    "Ialomița",
    "Ilfov",
    "Maramureș",
    "Mehedinți",
    "Mureș",
    "Neamț",
    "Olt",
    "Prahova",
    "Sălaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiș",
    "Tulcea",
    "Vâlcea",
    "Vaslui",
    "Vrancea",
  ],
  Russia: [
    "Republic of Adygeya",
    "Altai Republic",
    "Altai Krai",
    "Amur Oblast",
    "Arkhangelsk Oblast",
    "Astrakhan Oblast",
    "Republic of Bashkortostan",
    "Belgorod Oblast",
    "Bryansk Oblast",
    "Republic of Buryatia",
    "Chechen Republic",
    "Chelyabinsk Oblast",
    "Chukotka Autonomous Okrug",
    "Chuvash Republic",
    "Republic of Dagestan",
    "Republic of Ingushetia",
    "Irkutsk Oblast",
    "Ivanovo Oblast",
    "Jewish Autonomous Oblast",
    "Kabardino-Balkarian Republic",
    "Kaliningrad Oblast",
    "Republic of Kalmykia",
    "Kaluga Oblast",
    "Kamchatka Krai",
    "Karachay–Cherkess Republic",
    "Republic of Karelia",
    "Kemerovo Oblast",
    "Khabarovsk Krai",
    "Republic of Khakassia",
    "Khanty-Mansi Autonomous Okrug",
    "Kirov Oblast",
    "Komi Republic",
    "Kostroma Oblast",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Kurgan Oblast",
    "Kursk Oblast",
    "Leningrad Oblast",
    "Lipetsk Oblast",
    "Magadan Oblast",
    "Mari El Republic",
    "Republic of Mordovia",
    "Moscow",
    "Moscow Oblast",
    "Murmansk Oblast",
    "Nizhny Novgorod Oblast",
    "Novgorod Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Orenburg Oblast",
    "Oryol Oblast",
    "Penza Oblast",
    "Perm Krai",
    "Primorsky Krai",
    "Pskov Oblast",
    "Rostov Oblast",
    "Ryazan Oblast",
    "Saint Petersburg",
    "Sakha Republic (Yakutia)",
    "Sakhalin Oblast",
    "Samara Oblast",
    "Saratov Oblast",
    "Republic of North Ossetia–Alania",
    "Smolensk Oblast",
    "Stavropol Krai",
    "Sverdlovsk Oblast",
    "Tambov Oblast",
    "Republic of Tatarstan",
    "Tomsk Oblast",
    "Tula Oblast",
    "Tver Oblast",
    "Tyumen Oblast",
    "Tyva Republic",
    "Udmurtia",
    "Ulyanovsk Oblast",
    "Vladimir Oblast",
    "Volgograd Oblast",
    "Vologda Oblast",
    "Voronezh Oblast",
    "Yamalo-Nenets Autonomous Okrug",
    "Yaroslavl Oblast",
    "Zabaykalsky Krai",
  ],
  Rwanda: [],
  "Saint Barthélemy": [],
  "Saint Helena": [],
  "Saint Kitts And Nevis": [],
  "Saint Lucia": [],
  "Saint Martin": [],
  "Saint Pierre And Miquelon": [],
  Samoa: [],
  "San Marino": [],
  "Sao Tome And Principe": [],
  "Saudi Arabia": [],
  Senegal: [],
  Serbia: [],
  Seychelles: [],
  "Sierra Leone": [],
  Singapore: [],
  "Sint Maarten": [],
  Slovakia: [],
  Slovenia: [],
  "Solomon Islands": [],
  Somalia: [],
  "South Africa": [
    "Eastern Cape",
    "Free State",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "North West",
    "Northern Cape",
    "Western Cape",
  ],
  "South Georgia And The South Sandwich Islands": [],
  "South Korea": [
    "Busan",
    "Chungbuk",
    "Chungnam",
    "Daegu",
    "Daejeon",
    "Gangwon",
    "Gwangju",
    "Gyeongbuk",
    "Gyeonggi",
    "Gyeongnam",
    "Incheon",
    "Jeju",
    "Jeonbuk",
    "Jeonnam",
    "Sejong",
    "Seoul",
    "Ulsan",
  ],
  "South Sudan": [],
  Spain: [
    "A Coruña",
    "Álava",
    "Albacete",
    "Alicante",
    "Almería",
    "Asturias",
    "Ávila",
    "Badajoz",
    "Balears",
    "Barcelona",
    "Burgos",
    "Cáceres",
    "Cádiz",
    "Cantabria",
    "Castellón",
    "Ceuta",
    "Ciudad Real",
    "Córdoba",
    "Cuenca",
    "Girona",
    "Granada",
    "Guadalajara",
    "Guipúzcoa",
    "Huelva",
    "Huesca",
    "Jaén",
    "La Rioja",
    "Las Palmas",
    "León",
    "Lleida",
    "Lugo",
    "Madrid",
    "Málaga",
    "Melilla",
    "Murcia",
    "Navarra",
    "Ourense",
    "Palencia",
    "Pontevedra",
    "Salamanca",
    "Santa Cruz de Tenerife",
    "Segovia",
    "Sevilla",
    "Soria",
    "Tarragona",
    "Teruel",
    "Toledo",
    "Valencia",
    "Valladolid",
    "Vizcaya",
    "Zamora",
    "Zaragoza",
  ],
  "Sri Lanka": [],
  "St. Vincent": [],
  Sudan: [],
  Suriname: [],
  "Svalbard And Jan Mayen": [],
  Sweden: [],
  Switzerland: [],
  Syria: [],
  Taiwan: [],
  Tajikistan: [],
  "Tanzania, United Republic Of": [],
  Thailand: [
    "Amnat Charoen",
    "Ang Thong",
    "Bangkok",
    "Bueng Kan",
    "Buriram",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chon Buri",
    "Chumphon",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lopburi",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Nan",
    "Narathiwat",
    "Nong Bua Lam Phu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Pattaya",
    "Phangnga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phrae",
    "Phuket",
    "Prachin Buri",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Roi Et",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Satun",
    "Sing Buri",
    "Sisaket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Tak",
    "Trang",
    "Trat",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasothon",
  ],
  "Timor Leste": [],
  Togo: [],
  Tokelau: [],
  Tonga: [],
  "Trinidad and Tobago": [],
  "Tristan da Cunha": [],
  Tunisia: [],
  Turkey: [],
  Turkmenistan: [],
  "Turks and Caicos Islands": [],
  Tuvalu: [],
  Uganda: [],
  Ukraine: [],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Dubai",
    "Fujairah",
    "Ras al-Khaimah",
    "Sharjah",
    "Umm al-Quwain",
  ],
  "United Kingdom": [
    "British Forces",
    "England",
    "Northern Ireland",
    "Scotland",
    "Wales",
  ],
  "United States": [
    "Alabama",
    "Alaska",
    "American Samoa",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Federated States of Micronesia",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Marshall Islands",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Northern Mariana Islands",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Palau",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "Virgin Islands",
    "Armed Forces Americas",
    "Armed Forces Europe",
    "Armed Forces Pacific",
  ],
  "United States Minor Outlying Islands": [],
  Uruguay: [],
  Uzbekistan: [],
  Vanuatu: [],
  Venezuela: [],
  Vietnam: [],
  "Virgin Islands, British": [],
  "Wallis And Futuna": [],
  "Western Sahara": [],
  Yemen: [],
  Zambia: [],
  Zimbabwe: [],
};
