import { dataError, noInternetError } from "../../assets/images";
import i18next from "../../i18n";
export const PRODUCT_SORT_VALUES = {
  POPULARITY: "Popularity",
  RELEVANCE: "Relevance",
  PRICE_LOW_TO_HIGH: "Price from Low to High",
  PRICE_HIGH_TO_LOW: "Price from High to Low",
};
export const PRODUCT_SORT_VALUES_ARABIC = {
  POPULARITY: "الشعبية",
  RELEVANCE: "الصلة بموضوع البحث",
  PRICE_LOW_TO_HIGH: "السعر من الأقل إلى الأعلى",
  PRICE_HIGH_TO_LOW: "السعر من الأعلى إلى الأقل",
};

export const ERRORS = {
  noInternet: {
    title: "No Internet Connection",
    message: "Please check your internet settings and try again later",
    image: noInternetError,
  },
  data: {
    title: "Something Went Wrong",
    message:
      "We encountered some error while processing your request. Please try again later",
    image: dataError,
  },
};
export const ERRORS_ARABIC = {
  noInternet: {
    title: "لا يوجد اتصال بالإنترنت",
    message: "يرجى التحقق من إعدادات الإنترنت لديك والمحاولة مرة أخرى لاحقًا",
    image: noInternetError,
  },
  data: {
    title: "حدث خطأ ما",
    message:
      "نواجه بعض الأخطاء أثناء معالجة طلبك. الرجاء معاودة المحاولة في وقت لاحق",
    image: dataError,
  },
};

export const CheckoutErrorCode = {
  ALREADY_COMPLETED: "ALREADY_COMPLETED",
  BAD_DOMAIN: "BAD_DOMAIN",
  BLANK: "BLANK",
  CART_DOES_NOT_MEET_DISCOUNT_REQUIREMENTS_NOTICE:
    "CART_DOES_NOT_MEET_DISCOUNT_REQUIREMENTS_NOTICE",
  CUSTOMER_ALREADY_USED_ONCE_PER_CUSTOMER_DISCOUNT_NOTICE:
    "CUSTOMER_ALREADY_USED_ONCE_PER_CUSTOMER_DISCOUNT_NOTICE",
  DISCOUNT_ALREADY_APPLIED: "DISCOUNT_ALREADY_APPLIED",
  DISCOUNT_CODE_APPLICATION_FAILED: "DISCOUNT_CODE_APPLICATION_FAILED",
  DISCOUNT_DISABLED: "DISCOUNT_DISABLED",
  DISCOUNT_EXPIRED: "DISCOUNT_EXPIRED",
  DISCOUNT_LIMIT_REACHED: "DISCOUNT_LIMIT_REACHED",
  DISCOUNT_NOT_FOUND: "DISCOUNT_NOT_FOUND",
  EMPTY: "EMPTY",
  EXPIRED_QUEUE_TOKEN: "EXPIRED_QUEUE_TOKEN",
  GIFT_CARD_ALREADY_APPLIED: "GIFT_CARD_ALREADY_APPLIED",
  GIFT_CARD_CODE_INVALID: "GIFT_CARD_CODE_INVALID",
  GIFT_CARD_CURRENCY_MISMATCH: "GIFT_CARD_CURRENCY_MISMATCH",
  GIFT_CARD_DEPLETED: "GIFT_CARD_DEPLETED",
  GIFT_CARD_DISABLED: "GIFT_CARD_DISABLED",
  GIFT_CARD_EXPIRED: "GIFT_CARD_EXPIRED",
  GIFT_CARD_NOT_FOUND: "GIFT_CARD_NOT_FOUND",
  GIFT_CARD_UNUSABLE: "GIFT_CARD_UNUSABLE",
  GREATER_THAN_OR_EQUAL_TO: "GREATER_THAN_OR_EQUAL_TO",
  HIGHER_VALUE_DISCOUNT_APPLIED: "HIGHER_VALUE_DISCOUNT_APPLIED",
  INVALID: "INVALID",
  INVALID_COUNTRY_AND_CURRENCY: "INVALID_COUNTRY_AND_CURRENCY",
  INVALID_FOR_COUNTRY: "INVALID_FOR_COUNTRY",
  INVALID_FOR_COUNTRY_AND_PROVINCE: "INVALID_FOR_COUNTRY_AND_PROVINCE",
  INVALID_PROVINCE_IN_COUNTRY: "INVALID_PROVINCE_IN_COUNTRY",
  INVALID_QUEUE_TOKEN: "INVALID_QUEUE_TOKEN",
  INVALID_REGION_IN_COUNTRY: "INVALID_REGION_IN_COUNTRY",
  INVALID_STATE_IN_COUNTRY: "INVALID_STATE_IN_COUNTRY",
  LESS_THAN: "LESS_THAN",
  LESS_THAN_OR_EQUAL_TO: "LESS_THAN_OR_EQUAL_TO",
  LINE_ITEM_NOT_FOUND: "LINE_ITEM_NOT_FOUND",
  LOCKED: "LOCKED",
  MAXIMUM_DISCOUNT_CODE_LIMIT_REACHED: "MAXIMUM_DISCOUNT_CODE_LIMIT_REACHED",
  MISSING_PAYMENT_INPUT: "MISSING_PAYMENT_INPUT",
  NOT_ENOUGH_IN_STOCK: "NOT_ENOUGH_IN_STOCK",
  NOT_SUPPORTED: "NOT_SUPPORTED",
  PRESENT: "PRESENT",
  PRODUCT_NOT_AVAILABLE: "PRODUCT_NOT_AVAILABLE",
  SHIPPING_RATE_EXPIRED: "SHIPPING_RATE_EXPIRED",
  THROTTLED_DURING_CHECKOUT: "THROTTLED_DURING_CHECKOUT",
  TOO_LONG: "TOO_LONG",
  TOTAL_PRICE_MISMATCH: "TOTAL_PRICE_MISMATCH",
  UNABLE_TO_APPLY: "UNABLE_TO_APPLY",
};
