export const ProductCollectionSortKeys = {
  BEST_SELLING: "BEST_SELLING",
  COLLECTION_DEFAULT: "COLLECTION_DEFAULT",
  CREATED: "CREATED",
  ID: "ID",
  MANUAL: "MANUAL",
  PRICE: "PRICE",
  RELEVANCE: "RELEVANCE",
  TITLE: "TITLE",
};
