export const ProductCollectionSortKeys = {
  BEST_SELLING: "BEST_SELLING",
  COLLECTION_DEFAULT: "COLLECTION_DEFAULT",
  CREATED: "CREATED",
  ID: "ID",
  MANUAL: "MANUAL",
  PRICE: "PRICE",
  RELEVANCE: "RELEVANCE",
  TITLE: "TITLE",
};

export const ProductSortKeys = {
  BEST_SELLING: "BEST_SELLING",
  CREATED_AT: "CREATED_AT",
  ID: "ID",
  PRICE: "PRICE",
  PRODUCT_TYPE: "PRODUCT_TYPE",
  RELEVANCE: "RELEVANCE",
  TITLE: "TITLE",
  UPDATED_AT: "UPDATED_AT",
  VENDOR: "VENDOR",
};
